FROM openjdk:8-alpine
MAINTAINER Your Name <you@example.com>

ADD target/api-linguagens-formais-0.0.1-SNAPSHOT-standalone.jar /api-linguagens-formais/app.jar

EXPOSE 8080

CMD ["java", "-jar", "/api-linguagens-formais/app.jar"]
